name: EIP Odoo OpenMRS Integration Tests

on:
  repository_dispatch:
    types: [ trigger-workflow ]

jobs:
  spotless:
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-spotless-check.yml@main

  validate:
    needs: spotless
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-build-test.yml@main
    with:
      maven-args: '-pl eip-odoo-openmrs-it -am'
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
